[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = "1.2.6"
risc0-zkvm = { version = "1.2.6", features = ["heap-embedded-alloc"] }

[dependencies]
risc0-zkvm = "1.2.6"
